### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: qwen/qwen2.5-coder-1.5b-instruct
adapter_name_or_path: saves/adapters/qwen/3r/2e-4
template: qwen
trust_remote_code: true

### export
export_dir: saves/models/qwen/3r/2e-4
export_size: 5
export_device: auto  # choices: [cpu, auto]
export_legacy_format: false
